cc_library(
    name = "free_list",
    srcs = ["free_list.cc"],
    hdrs = ["free_list.h"],
    deps = [
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:string_view",
        "@cc-util//util:absl_util",
    ],
)
